"""
response_parser.py

Parses the response generated by the language model into
structured fields.
"""

import re
from typing import Dict


# ============================================================
# HELPERS
# ============================================================

def _clean_text(text: str) -> str:
    """
    Normalizes whitespace and removes simple markdown formatting.
    """

    if not text:
        return ""

    # Remove markdown heading markers
    text = re.sub(r"^#+\s*", "", text, flags=re.MULTILINE)

    # Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Remove excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Collapse repeated spaces
    text = re.sub(r"[ \t]+", " ", text)

    return text.strip()


def _is_invalid_headline(headline: str) -> bool:
    """
    Detects reasoning text or invalid headlines generated by the model.
    """

    if not headline:
        return True

    headline = headline.lower().strip()

    invalid_prefixes = (
        "maybe",
        "perhaps",
        "i think",
        "something like",
        "how about",
        "it could be",
        "it might be",
        "possibly",
    )

    return headline.startswith(invalid_prefixes)


# ============================================================
# PUBLIC API
# ============================================================

def parse_response(response: str) -> Dict:
    """
    Parses the model output into structured fields.
    """

    response = _clean_text(response)

    headline = ""
    article = response

    # Accept slight variations in labels
    headline_match = re.search(
        r"Headline\s*:\s*(.+)",
        response,
        flags=re.IGNORECASE,
    )

    article_match = re.search(
        r"Article\s*:\s*(.*)",
        response,
        flags=re.IGNORECASE | re.DOTALL,
    )

    if headline_match:
        headline = headline_match.group(1).strip()

    if article_match:
        article = article_match.group(1).strip()

    # Final cleanup
    headline = _clean_text(headline)
    article = _clean_text(article)

    # Remove surrounding quotation marks if present
    headline = headline.strip("\"'")

    # Reject reasoning instead of a proper headline
    if _is_invalid_headline(headline):
        headline = ""

    return {
        "headline": headline,
        "content": article,
    }