"""
response_parser.py

Parses and cleans the response generated by the language model.
"""

import re
from typing import Dict


# ============================================================
# TEXT CLEANING
# ============================================================

def _clean_text(text: str) -> str:
    """
    Normalizes whitespace and removes simple markdown formatting.
    """

    if not text:
        return ""

    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Remove markdown heading markers
    text = re.sub(r"^\s*#{1,6}\s*", "", text, flags=re.MULTILINE)

    # Remove excessive spaces/tabs
    text = re.sub(r"[ \t]+", " ", text)

    # Collapse excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


# ============================================================
# HEADLINE VALIDATION
# ============================================================

def _is_invalid_headline(headline: str) -> bool:
    """
    Detects reasoning or invalid text instead of a real headline.
    """

    if not headline:
        return True

    headline = headline.lower().strip()

    invalid_prefixes = (
        "maybe",
        "perhaps",
        "i think",
        "something like",
        "how about",
        "it could be",
        "it might be",
        "possibly",
        "here is",
        "headline",
    )

    return headline.startswith(invalid_prefixes)


# ============================================================
# EXTRACT HEADLINE
# ============================================================

def _extract_headline(response: str) -> str:
    """
    Extracts the headline from the model response.

    Supports both:

        Headline:
        <headline>

    and cases where the model simply starts with:

        <headline>
        <article>
    """

    # --------------------------------------------------------
    # Preferred format:
    #
    # Headline:
    # <headline>
    # --------------------------------------------------------

    match = re.search(
        r"^\s*Headline\s*:\s*(.+?)\s*$",
        response,
        flags=re.IGNORECASE | re.MULTILINE,
    )

    if match:
        return match.group(1).strip()

    # --------------------------------------------------------
    # Markdown format:
    #
    # # <headline>
    # --------------------------------------------------------

    match = re.search(
        r"^\s*#{1,2}\s+(.+?)\s*$",
        response,
        flags=re.MULTILINE,
    )

    if match:
        return match.group(1).strip()

    # --------------------------------------------------------
    # If the model does not provide a label, use the first
    # non-empty line as the headline.
    # --------------------------------------------------------

    lines = [
        line.strip()
        for line in response.split("\n")
        if line.strip()
    ]

    if lines:
        first_line = lines[0]

        if not first_line.lower().startswith("article:"):
            return first_line

    return ""


# ============================================================
# EXTRACT ARTICLE
# ============================================================

def _extract_article(response: str) -> str:
    """
    Extracts the article body.

    Supports:

        Article:
        <article>

    and unlabeled responses where the first line is the headline.
    """

    # --------------------------------------------------------
    # Preferred format:
    #
    # Article:
    # <article>
    # --------------------------------------------------------

    match = re.search(
        r"^\s*Article\s*:\s*(.*)$",
        response,
        flags=re.IGNORECASE | re.MULTILINE | re.DOTALL,
    )

    if match:
        return match.group(1).strip()

    # --------------------------------------------------------
    # Unlabeled response:
    #
    # First line = headline
    # Remaining text = article
    # --------------------------------------------------------

    lines = [
        line.strip()
        for line in response.split("\n")
        if line.strip()
    ]

    if len(lines) > 1:
        return "\n\n".join(lines[1:])

    return ""


# ============================================================
# PUBLIC API
# ============================================================

def parse_response(response: str) -> Dict:
    """
    Parses the model output into structured fields.
    """

    response = _clean_text(response)

    headline = _extract_headline(response)
    article = _extract_article(response)

    headline = _clean_text(headline).strip("\"'")

    article = _clean_text(article)

    if _is_invalid_headline(headline):
        headline = ""

    return {
        "headline": headline,
        "content": article,
    }