"""
response_parser.py

Parses and cleans the response generated by the language model.
"""

import re
from typing import Dict


# ============================================================
# HELPERS
# ============================================================

def _clean_text(text: str) -> str:
    """
    Normalizes whitespace and removes simple markdown formatting.
    """

    if not text:
        return ""

    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Remove markdown headings
    text = re.sub(r"^#+\s*", "", text, flags=re.MULTILINE)

    # Collapse repeated spaces
    text = re.sub(r"[ \t]+", " ", text)

    # Collapse excessive blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def _is_invalid_headline(headline: str) -> bool:
    """
    Detects reasoning instead of a real headline.
    """

    if not headline:
        return True

    headline = headline.lower().strip()

    invalid_prefixes = (
        "maybe",
        "perhaps",
        "i think",
        "something like",
        "how about",
        "it could be",
        "it might be",
        "possibly",
        "here is",
        "headline",
    )

    return headline.startswith(invalid_prefixes)


def _extract_headline(response: str) -> str:
    """
    Extracts the headline from the model response.
    """

    patterns = [

        r"Headline\s*:\s*(.+)",

        r"^Headline\s*\n+(.+)",

        r"^#\s*(.+)",

        r"^##\s*(.+)",
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            response,
            flags=re.IGNORECASE | re.MULTILINE,
        )

        if match:

            return match.group(1).strip()

    return ""


def _extract_article(response: str) -> str:
    """
    Extracts the article body.
    """

    patterns = [

        r"Article\s*:\s*(.*)",

        r"^Article\s*\n+(.*)",

    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            response,
            flags=re.IGNORECASE | re.DOTALL | re.MULTILINE,
        )

        if match:

            return match.group(1).strip()

    return response


# ============================================================
# PUBLIC API
# ============================================================

def parse_response(response: str) -> Dict:
    """
    Parses the model output into structured fields.
    """

    response = _clean_text(response)

    headline = _extract_headline(response)

    article = _extract_article(response)

    headline = _clean_text(headline).strip("\"'")

    article = _clean_text(article)

    if _is_invalid_headline(headline):
        headline = ""

    return {
        "headline": headline,
        "content": article,
    }